import { safeWriteFileSync } from '../utils/safeWrite.js';

export function generatePonderConfig(): string {
  return `// This file is auto-generated by zonder. Do not edit manually.
import { zonderConfig } from "./zonder.config";

export default zonderConfig.toPonder();
`;
}

export function generateAndWritePonderConfig(
  outputPath = './ponder.config.ts',
  overwrite = false,
): void {
  const content = generatePonderConfig();
  safeWriteFileSync(outputPath, content, { overwrite });
}
