import fs from 'fs';

export function generatePonderConfig(): string {
  return `// This file is auto-generated by zonder. Do not edit manually.
import { zonderConfig } from "./zonder.config";

export default zonderConfig.toPonder();
`;
}

export function generateAndWritePonderConfig(outputPath = './ponder.config.ts'): void {
  const content = generatePonderConfig();
  fs.writeFileSync(outputPath, content);
}
